#!/bin/bash
#
# SharedBrain One-Liner Installer
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/awictor/shared-brain/main/install.sh | bash
#
# Or download and run locally:
#   chmod +x install.sh && ./install.sh
#

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RESET='\033[0m'

# Helpers
log() { echo -e "${GREEN}[shared-brain]${RESET} $1"; }
warn() { echo -e "${YELLOW}[warning]${RESET} $1"; }
error() { echo -e "${RED}[error]${RESET} $1"; exit 1; }

# Banner
echo ""
echo -e "${BLUE}╔════════════════════════════════════════╗${RESET}"
echo -e "${BLUE}║                                        ║${RESET}"
echo -e "${BLUE}║         SharedBrain Installer          ║${RESET}"
echo -e "${BLUE}║                                        ║${RESET}"
echo -e "${BLUE}║  Local-first memory for AI agents     ║${RESET}"
echo -e "${BLUE}║                                        ║${RESET}"
echo -e "${BLUE}╚════════════════════════════════════════╝${RESET}"
echo ""

# Check Node.js version
log "Checking Node.js version..."
if ! command -v node &> /dev/null; then
  error "Node.js not found. Please install Node.js ≥ 20.0.0 from https://nodejs.org/"
fi

NODE_VERSION=$(node --version | cut -d'v' -f2)
NODE_MAJOR=$(echo "$NODE_VERSION" | cut -d'.' -f1)

if [ "$NODE_MAJOR" -lt 20 ]; then
  error "Node.js $NODE_VERSION found, but ≥ 20.0.0 required. Please upgrade: https://nodejs.org/"
fi

log "✓ Node.js $NODE_VERSION detected"

# Check for package manager
if command -v pnpm &> /dev/null; then
  PKG_MANAGER="pnpm"
  log "✓ Using pnpm"
elif command -v npm &> /dev/null; then
  PKG_MANAGER="npm"
  log "✓ Using npm"
else
  error "No package manager found. Please install npm or pnpm."
fi

# Determine install location
INSTALL_DIR="${SHARED_BRAIN_INSTALL_DIR:-$HOME/shared-brain}"

if [ -d "$INSTALL_DIR" ]; then
  warn "Directory $INSTALL_DIR already exists."
  read -p "Overwrite? (y/N): " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    error "Installation cancelled."
  fi
  log "Removing existing installation..."
  rm -rf "$INSTALL_DIR"
fi

# Clone repository
log "Cloning SharedBrain repository..."
if ! git clone https://github.com/awictor/shared-brain.git "$INSTALL_DIR" &> /dev/null; then
  error "Failed to clone repository. Check your internet connection."
fi
log "✓ Repository cloned to $INSTALL_DIR"

# Navigate to server package
cd "$INSTALL_DIR/packages/server"

# Install dependencies
log "Installing dependencies (this may take a minute)..."
if [ "$PKG_MANAGER" = "pnpm" ]; then
  pnpm install --silent &> /dev/null || error "pnpm install failed"
else
  npm install --silent --loglevel=error &> /dev/null || error "npm install failed"
fi
log "✓ Dependencies installed"

# Build
log "Building SharedBrain..."
if [ "$PKG_MANAGER" = "pnpm" ]; then
  pnpm build &> /dev/null || error "Build failed"
else
  npm run build &> /dev/null || error "Build failed"
fi
log "✓ Build complete"

# Generate JWT secret (if not already set)
if [ -z "$JWT_SECRET" ]; then
  JWT_SECRET=$(openssl rand -base64 32 2>/dev/null || head -c 32 /dev/urandom | base64)
fi

# Create .env file
ENV_FILE="$INSTALL_DIR/packages/server/.env"
cat > "$ENV_FILE" <<EOF
# SharedBrain Configuration
# Generated by install.sh on $(date)

# Server
PORT=3100
HOST=127.0.0.1
NODE_ENV=production

# Database
DB_PATH=$HOME/.shared-brain/brain.db

# Auth
JWT_SECRET=$JWT_SECRET

# Limits
MAX_MEMORIES_PER_USER=10000

# Optional: uncomment to enable team sync
# SYNC_RELAY_URL=ws://localhost:3200
# SYNC_AUTH_TOKEN=your-sync-token-here

# Optional: uncomment to restrict CORS origins
# ALLOWED_ORIGINS=https://your-domain.com,https://api.your-domain.com

# Ingest webhook token (for /ingest/* endpoints)
INGEST_TOKEN=$(openssl rand -hex 16 2>/dev/null || head -c 16 /dev/urandom | xxd -p)
EOF

log "✓ Configuration saved to $ENV_FILE"

# Create data directory
mkdir -p "$HOME/.shared-brain"
log "✓ Data directory created at $HOME/.shared-brain"

# Start server in background
log "Starting SharedBrain server..."
PORT=3100
if [ "$PKG_MANAGER" = "pnpm" ]; then
  pnpm start > "$HOME/.shared-brain/server.log" 2>&1 &
else
  npm start > "$HOME/.shared-brain/server.log" 2>&1 &
fi
SERVER_PID=$!

# Wait for server to be ready (max 30 seconds)
log "Waiting for server to be ready..."
MAX_WAIT=30
WAITED=0
while ! curl -s http://127.0.0.1:$PORT/health/ready > /dev/null 2>&1; do
  if [ $WAITED -ge $MAX_WAIT ]; then
    warn "Server did not start within ${MAX_WAIT}s. Check logs at $HOME/.shared-brain/server.log"
    break
  fi
  sleep 1
  WAITED=$((WAITED + 1))
done

if curl -s http://127.0.0.1:$PORT/health/ready > /dev/null 2>&1; then
  log "✓ Server running at http://127.0.0.1:$PORT (PID: $SERVER_PID)"
else
  error "Server failed to start. Check logs: tail -f $HOME/.shared-brain/server.log"
fi

# Generate a sample JWT token
log "Generating authentication token..."
USER_ID="${USER:-$(whoami)}"
USER_NAME="$USER_ID"

TOKEN_RESPONSE=$(curl -s "http://127.0.0.1:$PORT/api/auth/token?userId=$USER_ID&userName=$USER_NAME" 2>/dev/null)
TOKEN=$(echo "$TOKEN_RESPONSE" | grep -o '"token":"[^"]*"' | cut -d'"' -f4)

if [ -z "$TOKEN" ]; then
  warn "Failed to generate token automatically. Generate one manually:"
  echo "  curl \"http://127.0.0.1:$PORT/api/auth/token?userId=YOUR_ID&userName=YOUR_NAME\""
  TOKEN="<YOUR_TOKEN_HERE>"
fi

# Print MCP configuration
echo ""
echo -e "${GREEN}╔════════════════════════════════════════════════════════════════╗${RESET}"
echo -e "${GREEN}║                                                                ║${RESET}"
echo -e "${GREEN}║                  Installation Complete!                        ║${RESET}"
echo -e "${GREEN}║                                                                ║${RESET}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════════════╝${RESET}"
echo ""
log "SharedBrain is running at: ${BLUE}http://127.0.0.1:$PORT${RESET}"
log "Dashboard: ${BLUE}http://127.0.0.1:$PORT/app${RESET}"
log "Server logs: ${BLUE}$HOME/.shared-brain/server.log${RESET}"
log "Database: ${BLUE}$HOME/.shared-brain/brain.db${RESET}"
echo ""
echo -e "${YELLOW}Next steps:${RESET}"
echo ""
echo "1. Add SharedBrain to your AI agent's MCP config:"
echo ""

if command -v claude &> /dev/null || [ -d "$HOME/.claude" ]; then
  echo "   ${BLUE}Claude Code${RESET} (~/.claude/settings.json):"
  echo ""
  cat <<'CLAUDE'
   {
     "mcpServers": {
       "shared-brain": {
         "type": "streamable-http",
         "url": "http://127.0.0.1:3100/mcp",
         "headers": {
           "Authorization": "Bearer TOKEN_PLACEHOLDER"
         }
       }
     }
   }
CLAUDE
  echo ""
fi

if command -v cursor &> /dev/null || [ -d "$HOME/.cursor" ]; then
  echo "   ${BLUE}Cursor${RESET} (~/.cursor/mcp.json):"
  echo ""
  cat <<'CURSOR'
   {
     "mcpServers": {
       "shared-brain": {
         "url": "http://127.0.0.1:3100/mcp",
         "transport": "streamable-http",
         "headers": {
           "Authorization": "Bearer TOKEN_PLACEHOLDER"
         }
       }
     }
   }
CURSOR
  echo ""
fi

echo "   ${BLUE}VS Code / GitHub Copilot${RESET} (project .vscode/mcp.json):"
echo ""
cat <<'VSCODE'
   {
     "servers": {
       "shared-brain": {
         "type": "http",
         "url": "http://127.0.0.1:3100/mcp",
         "headers": {
           "Authorization": "Bearer TOKEN_PLACEHOLDER"
         }
       }
     }
   }
VSCODE
echo ""
echo "2. Replace ${YELLOW}TOKEN_PLACEHOLDER${RESET} with your token:"
echo ""
echo "   ${GREEN}$TOKEN${RESET}"
echo ""
echo "3. Restart your agent and try:"
echo ""
echo "   ${BLUE}\"Remember that we use SharedBrain for persistent memory\"${RESET}"
echo ""
echo "4. To manage the server:"
echo ""
echo "   Start:  ${BLUE}cd $INSTALL_DIR/packages/server && npm start${RESET}"
echo "   Stop:   ${BLUE}kill $SERVER_PID${RESET} (or ${BLUE}pkill -f shared-brain${RESET})"
echo "   Logs:   ${BLUE}tail -f $HOME/.shared-brain/server.log${RESET}"
echo ""
echo "5. For team collaboration, see: ${BLUE}http://127.0.0.1:$PORT/join${RESET}"
echo ""
echo -e "${GREEN}Happy brain-sharing!${RESET}"
echo ""
